name: "Test and deploy db"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        shell: "nix develop -c bash -e {0}"
        run: bun install

      - name: Start database
        run: bun run supabase db start
        shell: "nix develop -c bash -e {0}"

      - name: Test database
        run: bun run supabase test db
        shell: "nix develop -c bash -e {0}"

      - name: Link database
        run: bun run supabase link --project-ref ${{ vars.SUPABASE_PROJECT_ID }}
        shell: "nix develop -c bash -e {0}"

      - name: push database
        run: bun run supabase db push
        shell: "nix develop -c bash -e {0}"
